  spring:
    application:
      name: CamundaTemplate
    datasource.url: jdbc:h2:file:./camunda-h2-database

  camunda:
    bpm:
      auto-deployment-enabled: true
      deployment-resource-pattern: bpmn/**/*.bpmn
      history-level: full

  camunda.bpm.admin-user:
    id: admin
    password: admin
