logging:
  level:
    org.camunda.bpm.engine: INFO
    org.springframework.jdbc: TRACE

# Camunda & H2:

spring:
  application:
    name: CamundaTemplate
  datasource.url: jdbc:h2:file:./camunda-h2-database

camunda:
  bpm:
    auto-deployment-enabled: true
    deployment-resource-pattern: bpmn/**/*.bpmn
    history-level: full

camunda.bpm.admin-user:
  id: admin
  password: admin

# Camunda & Postgres:

#spring:
#  jpa:
#    properties:
#      hibernate:
#        default_schema: camunda
#  application:
#    name: CamundaTemplate
#  datasource:
#    url: jdbc:postgresql://localhost:5432/camunda?currentSchema=camunda
#    username: camunda
#    password: camunda
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      pool-name: CamundaHikariPool
#
#camunda:
#  bpm:
#    auto-deployment-enabled: true
#    deployment-resource-pattern: bpmn/**/*.bpmn
#    history-level: full
#    database:
#      type: postgres
#      schema-update: true
#      table-prefix: camunda.
#      schema-name: camunda
#
#camunda.bpm.admin-user:
#  id: admin
#  password: admin
#
#app:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/myapp
#    username: myapp
#    password: myapp123
#    driver-class-name: org.postgresql.Driver
